tasks:
    series:
        rss:
            - http://www.dailytvtorrents.org/rss/show/the-walking-dead
            - http://www.dailytvtorrents.org/rss/show/doctor-who
            - http://www.dailytvtorrents.org/rss/show/game-of-thrones
            - http://www.dailytvtorrents.org/rss/show/spartacus
            - http://www.dailytvtorrents.org/rss/show/fringe
            - http://www.dailytvtorrents.org/rss/show/modern-family
        series:
            quality: <=720p
            following:
                - Doctor Who
                - Spartacus
                - The walking dead
        transmission:
            host: "127.0.0.1"
            port: 9091
            username: test
            password: testtest